/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// It is auto-generated by Next.js and will be overwritten.
// see https://nextjs.org/docs/app/building-your-application/configuring/typescript
