apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: atlas-connect
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          command:
            - redis-server
            - '--appendonly'
            - 'yes'
            - '--maxmemory'
            - '512mb'
            - '--maxmemory-policy'
            - 'allkeys-lru'
            - '--save'
            - '60 1'
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: '100m'
              memory: '128Mi'
            limits:
              cpu: '500m'
              memory: '640Mi'
          readinessProbe:
            exec:
              command: ['redis-cli', 'ping']
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: atlas-connect
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None
