import type { CBLEntityKind, CBLFieldKind } from '@seltriva/semantic-engine';

/**
 * Friendly, business-facing names ("Product", "expirationDate") a caller
 * writes an intent with, mapped onto the CBL vocabulary the Canonical
 * Business Model (46.11) actually stores entities/fields under.
 */
export const ENTITY_ALIASES: Readonly<Record<string, CBLEntityKind>> = {
  product: 'PRODUCT',
  inventory: 'INVENTORY',
  stock: 'INVENTORY',
  customer: 'CUSTOMER',
  supplier: 'SUPPLIER',
  category: 'CATEGORY',
  brand: 'BRAND',
  unit: 'UNIT_OF_MEASURE',
  store: 'BRANCH',
  branch: 'BRANCH',
  warehouse: 'WAREHOUSE',
  employee: 'EMPLOYEE',
  promotion: 'PROMOTION',
  invoice: 'INVOICE',
  order: 'ORDER',
  orderline: 'ORDER_LINE',
  purchaseorder: 'PURCHASE_ORDER',
  purchaseorderline: 'PURCHASE_ORDER_LINE',
};

export const FIELD_ALIASES: Readonly<Record<string, CBLFieldKind>> = {
  id: 'ID',
  code: 'CODE',
  sku: 'SKU',
  ean: 'EAN',
  barcode: 'BARCODE',
  name: 'NAME',
  description: 'DESCRIPTION',
  costprice: 'COST_PRICE',
  saleprice: 'SALE_PRICE',
  margin: 'MARGIN',
  quantity: 'QUANTITY',
  minimumquantity: 'MINIMUM_QUANTITY',
  maximumquantity: 'MAXIMUM_QUANTITY',
  stockbalance: 'STOCK_BALANCE',
  weight: 'WEIGHT',
  expirationdate: 'EXPIRATION_DATE',
  manufacturedate: 'MANUFACTURE_DATE',
  status: 'STATUS',
  brand: 'BRAND',
  createdat: 'CREATED_AT',
  updatedat: 'UPDATED_AT',
};

/** Coarse value-kind per field alias — enough to catch obviously wrong operator/value combinations. */
export type FieldValueKind = 'string' | 'number' | 'date' | 'boolean';

export const FIELD_VALUE_KINDS: Readonly<Record<CBLFieldKind, FieldValueKind>> = {
  ID: 'string',
  CODE: 'string',
  EXTERNAL_CODE: 'string',
  INTERNAL_CODE: 'string',
  PRODUCT_CODE: 'string',
  CUSTOMER_CODE: 'string',
  SUPPLIER_CODE: 'string',
  ORDER_NUMBER: 'string',
  INVOICE_NUMBER: 'string',
  DOCUMENT_NUMBER: 'string',
  SERIES: 'string',
  SEQUENCE: 'number',
  NAME: 'string',
  SHORT_NAME: 'string',
  DESCRIPTION: 'string',
  NOTES: 'string',
  PRODUCT_NAME: 'string',
  BARCODE: 'string',
  GTIN: 'string',
  SKU: 'string',
  EAN: 'string',
  ISBN: 'string',
  NCM: 'string',
  CEST: 'string',
  CFOP: 'string',
  COST_PRICE: 'number',
  SALE_PRICE: 'number',
  MINIMUM_PRICE: 'number',
  MAXIMUM_PRICE: 'number',
  AVERAGE_PRICE: 'number',
  REFERENCE_PRICE: 'number',
  LIST_PRICE: 'number',
  MARGIN: 'number',
  MARKUP: 'number',
  DISCOUNT_RATE: 'number',
  DISCOUNT_AMOUNT: 'number',
  QUANTITY: 'number',
  MINIMUM_QUANTITY: 'number',
  MAXIMUM_QUANTITY: 'number',
  REORDER_POINT: 'number',
  STOCK_BALANCE: 'number',
  RESERVED_QUANTITY: 'number',
  AVAILABLE_QUANTITY: 'number',
  UNIT_OF_MEASURE: 'string',
  WEIGHT: 'number',
  LENGTH: 'number',
  WIDTH: 'number',
  HEIGHT: 'number',
  VOLUME: 'number',
  CREATED_AT: 'date',
  UPDATED_AT: 'date',
  DELETED_AT: 'date',
  EXPIRATION_DATE: 'date',
  MANUFACTURE_DATE: 'date',
  ISSUE_DATE: 'date',
  DUE_DATE: 'date',
  DELIVERY_DATE: 'date',
  ENTRY_DATE: 'date',
  EXIT_DATE: 'date',
  PAYMENT_DATE: 'date',
  DATE: 'date',
  CREATED_BY: 'string',
  UPDATED_BY: 'string',
  DELETED_BY: 'string',
  STATUS: 'string',
  STATE: 'string',
  PHASE: 'string',
  IS_ACTIVE: 'boolean',
  IS_DELETED: 'boolean',
  IS_ARCHIVED: 'boolean',
  IS_DIGITAL: 'boolean',
  IS_SERVICE: 'boolean',
  IS_TAXABLE: 'boolean',
  SUPPLIER: 'string',
  CUSTOMER: 'string',
  CATEGORY: 'string',
  SUBCATEGORY: 'string',
  BRAND: 'string',
  PRODUCT: 'string',
  ORDER: 'string',
  INVOICE: 'string',
  EMPLOYEE: 'string',
  DEPARTMENT: 'string',
  BRANCH: 'string',
  WAREHOUSE: 'string',
  PAYMENT_METHOD: 'string',
  CURRENCY: 'string',
  PRICE_LIST: 'string',
  CARRIER: 'string',
  ADDRESS_STREET: 'string',
  ADDRESS_NUMBER: 'string',
  ADDRESS_COMPLEMENT: 'string',
  ADDRESS_NEIGHBORHOOD: 'string',
  ADDRESS_CITY: 'string',
  ADDRESS_STATE: 'string',
  ADDRESS_POSTAL_CODE: 'string',
  ADDRESS_COUNTRY: 'string',
  LATITUDE: 'number',
  LONGITUDE: 'number',
  PHONE: 'string',
  MOBILE: 'string',
  EMAIL: 'string',
  WEBSITE: 'string',
  TAX_ID: 'string',
  COMPANY_REGISTRATION: 'string',
  STATE_REGISTRATION: 'string',
  MUNICIPAL_REGISTRATION: 'string',
  TAX_RATE: 'number',
  TAX_CODE: 'string',
  FISCAL_CLASS: 'string',
  PAYMENT_CONDITION: 'string',
  PAYMENT_TERM: 'string',
  AMOUNT: 'number',
  TOTAL_AMOUNT: 'number',
  NET_AMOUNT: 'number',
  TAX_AMOUNT: 'number',
  FREIGHT_AMOUNT: 'number',
  ACCOUNT_CODE: 'string',
  COST_CENTER_CODE: 'string',
  SORT_ORDER: 'number',
  VERSION: 'string',
  METADATA: 'string',
};

/** Canonical, ERP-independent relationships between business entity kinds — a fixed part of the business language, not derived per-tenant. */
export interface CanonicalRelationship {
  readonly alias: string;
  readonly toEntity: CBLEntityKind;
}

export const CANONICAL_RELATIONSHIPS: Readonly<
  Partial<Record<CBLEntityKind, readonly CanonicalRelationship[]>>
> = {
  INVENTORY: [
    { alias: 'product', toEntity: 'PRODUCT' },
    { alias: 'store', toEntity: 'BRANCH' },
    { alias: 'branch', toEntity: 'BRANCH' },
    { alias: 'warehouse', toEntity: 'WAREHOUSE' },
  ],
  INVENTORY_MOVEMENT: [
    { alias: 'product', toEntity: 'PRODUCT' },
    { alias: 'branch', toEntity: 'BRANCH' },
  ],
  PRODUCT: [
    { alias: 'category', toEntity: 'CATEGORY' },
    { alias: 'supplier', toEntity: 'SUPPLIER' },
    { alias: 'brand', toEntity: 'BRAND' },
    { alias: 'unit', toEntity: 'UNIT_OF_MEASURE' },
  ],
  ORDER: [{ alias: 'customer', toEntity: 'CUSTOMER' }],
  ORDER_LINE: [
    { alias: 'order', toEntity: 'ORDER' },
    { alias: 'product', toEntity: 'PRODUCT' },
  ],
  PURCHASE_ORDER: [{ alias: 'supplier', toEntity: 'SUPPLIER' }],
  PURCHASE_ORDER_LINE: [
    { alias: 'purchaseOrder', toEntity: 'PURCHASE_ORDER' },
    { alias: 'product', toEntity: 'PRODUCT' },
  ],
  INVOICE: [{ alias: 'customer', toEntity: 'CUSTOMER' }],
  PRICE_LIST_ITEM: [{ alias: 'product', toEntity: 'PRODUCT' }],
};

export function resolveEntityAlias(name: string): CBLEntityKind | null {
  return ENTITY_ALIASES[name.toLowerCase()] ?? null;
}

export function resolveFieldAlias(name: string): CBLFieldKind | null {
  return FIELD_ALIASES[name.toLowerCase().replace(/[_-]/g, '')] ?? null;
}
