import type { WorkflowTemplate, WorkflowGraph } from './types.js';

function makeGraph(
  nodes: WorkflowTemplate['graph']['nodes'],
  edges: WorkflowTemplate['graph']['edges']
): WorkflowGraph {
  return { nodes, edges };
}

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'tpl-erp-ecommerce',
    name: 'ERP → E-commerce Sync',
    description:
      'Sincroniza produtos, estoque e preços do ERP para a plataforma de e-commerce em tempo real.',
    category: 'Integração ERP',
    tags: ['erp', 'ecommerce', 'produtos', 'estoque'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'schedule',
          label: 'Agendamento 5min',
          config: { cron: '*/5 * * * *' },
          position: { x: 100, y: 100 },
        },
        {
          id: 'n2',
          type: 'http',
          label: 'Buscar Produtos ERP',
          config: { method: 'GET', url: '{{ERP_URL}}/products' },
          position: { x: 300, y: 100 },
        },
        {
          id: 'n3',
          type: 'transform',
          label: 'Mapear para Ecommerce',
          config: { mapping: 'erp_to_ecommerce' },
          position: { x: 500, y: 100 },
        },
        {
          id: 'n4',
          type: 'validate',
          label: 'Validar Dados',
          config: { schema: 'product_schema' },
          position: { x: 700, y: 100 },
        },
        {
          id: 'n5',
          type: 'condition',
          label: 'Tem Erros?',
          config: { expression: 'errors.length > 0' },
          position: { x: 900, y: 100 },
        },
        {
          id: 'n6',
          type: 'http',
          label: 'Enviar para Ecommerce',
          config: { method: 'POST', url: '{{ECOM_URL}}/products' },
          position: { x: 1100, y: 50 },
        },
        {
          id: 'n7',
          type: 'notification',
          label: 'Alertar Erros',
          config: { channel: 'slack', message: 'Sync error' },
          position: { x: 1100, y: 200 },
        },
        {
          id: 'n8',
          type: 'log',
          label: 'Registrar Sync',
          config: { level: 'info' },
          position: { x: 1300, y: 50 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n2', target: 'n3' },
        { id: 'e3', source: 'n3', target: 'n4' },
        { id: 'e4', source: 'n4', target: 'n5' },
        { id: 'e5', source: 'n5', target: 'n6', label: 'false' },
        { id: 'e6', source: 'n5', target: 'n7', label: 'true' },
        { id: 'e7', source: 'n6', target: 'n8' },
      ]
    ),
  },
  {
    id: 'tpl-erp-wms',
    name: 'ERP → WMS Inventory',
    description:
      'Sincroniza movimentações de estoque entre ERP e sistema de gerenciamento de armazém (WMS).',
    category: 'Integração ERP',
    tags: ['erp', 'wms', 'estoque', 'armazem'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'webhook',
          label: 'Receber Movimentação',
          config: { path: '/inventory-move' },
          position: { x: 100, y: 100 },
        },
        {
          id: 'n2',
          type: 'validate',
          label: 'Validar Entrada',
          config: { schema: 'inventory_move' },
          position: { x: 300, y: 100 },
        },
        {
          id: 'n3',
          type: 'transform',
          label: 'Formatar WMS',
          config: { mapping: 'erp_to_wms' },
          position: { x: 500, y: 100 },
        },
        {
          id: 'n4',
          type: 'http',
          label: 'Atualizar WMS',
          config: { method: 'PUT', url: '{{WMS_URL}}/inventory' },
          position: { x: 700, y: 100 },
        },
        {
          id: 'n5',
          type: 'log',
          label: 'Auditar Movimentação',
          config: { level: 'info' },
          position: { x: 900, y: 100 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n2', target: 'n3' },
        { id: 'e3', source: 'n3', target: 'n4' },
        { id: 'e4', source: 'n4', target: 'n5' },
      ]
    ),
  },
  {
    id: 'tpl-erp-bi',
    name: 'ERP → BI Pipeline',
    description: 'Extrai dados do ERP, transforma e carrega no data warehouse para análise de BI.',
    category: 'Analytics',
    tags: ['erp', 'bi', 'etl', 'analytics', 'datawarehouse'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'schedule',
          label: 'ETL Noturno',
          config: { cron: '0 2 * * *' },
          position: { x: 100, y: 100 },
        },
        {
          id: 'n2',
          type: 'http',
          label: 'Extrair Vendas',
          config: { method: 'GET', url: '{{ERP_URL}}/sales?period=today' },
          position: { x: 300, y: 50 },
        },
        {
          id: 'n3',
          type: 'http',
          label: 'Extrair Clientes',
          config: { method: 'GET', url: '{{ERP_URL}}/customers' },
          position: { x: 300, y: 200 },
        },
        {
          id: 'n4',
          type: 'merge',
          label: 'Consolidar Dados',
          config: {},
          position: { x: 550, y: 125 },
        },
        {
          id: 'n5',
          type: 'transform',
          label: 'Dimensionalizar',
          config: { mapping: 'erp_to_star_schema' },
          position: { x: 750, y: 125 },
        },
        {
          id: 'n6',
          type: 'ai-summarize',
          label: 'Sumário IA',
          config: { model: 'claude-opus-4-8' },
          position: { x: 950, y: 125 },
        },
        {
          id: 'n7',
          type: 'database-write',
          label: 'Gravar no DW',
          config: { table: 'fact_sales' },
          position: { x: 1150, y: 125 },
        },
        {
          id: 'n8',
          type: 'log',
          label: 'Log ETL',
          config: { level: 'info' },
          position: { x: 1350, y: 125 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n1', target: 'n3' },
        { id: 'e3', source: 'n2', target: 'n4' },
        { id: 'e4', source: 'n3', target: 'n4' },
        { id: 'e5', source: 'n4', target: 'n5' },
        { id: 'e6', source: 'n5', target: 'n6' },
        { id: 'e7', source: 'n6', target: 'n7' },
        { id: 'e8', source: 'n7', target: 'n8' },
      ]
    ),
  },
  {
    id: 'tpl-erp-crm',
    name: 'ERP → CRM Customer Sync',
    description: 'Sincroniza dados de clientes e histórico de pedidos do ERP para o CRM.',
    category: 'Integração ERP',
    tags: ['erp', 'crm', 'clientes', 'vendas'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'webhook',
          label: 'Novo Cliente ERP',
          config: { path: '/customer-created' },
          position: { x: 100, y: 100 },
        },
        {
          id: 'n2',
          type: 'ai-classify',
          label: 'Classificar Cliente',
          config: { model: 'claude-opus-4-8', task: 'customer_segment' },
          position: { x: 300, y: 100 },
        },
        {
          id: 'n3',
          type: 'transform',
          label: 'Mapear para CRM',
          config: { mapping: 'erp_to_crm' },
          position: { x: 500, y: 100 },
        },
        {
          id: 'n4',
          type: 'http',
          label: 'Criar no CRM',
          config: { method: 'POST', url: '{{CRM_URL}}/contacts' },
          position: { x: 700, y: 100 },
        },
        {
          id: 'n5',
          type: 'notification',
          label: 'Notificar Vendedor',
          config: { channel: 'email' },
          position: { x: 900, y: 100 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n2', target: 'n3' },
        { id: 'e3', source: 'n3', target: 'n4' },
        { id: 'e4', source: 'n4', target: 'n5' },
      ]
    ),
  },
  {
    id: 'tpl-erp-marketplace',
    name: 'ERP → Marketplace',
    description:
      'Publica e atualiza produtos em marketplaces (Mercado Livre, Amazon, Shopee) a partir do ERP.',
    category: 'Integração ERP',
    tags: ['erp', 'marketplace', 'produtos', 'ml', 'amazon'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'trigger',
          label: 'Produto Atualizado',
          config: { event: 'product.updated' },
          position: { x: 100, y: 150 },
        },
        {
          id: 'n2',
          type: 'split',
          label: 'Por Marketplace',
          config: { key: 'marketplace' },
          position: { x: 300, y: 150 },
        },
        {
          id: 'n3',
          type: 'transform',
          label: 'Formato ML',
          config: { mapping: 'to_mercadolivre' },
          position: { x: 500, y: 50 },
        },
        {
          id: 'n4',
          type: 'transform',
          label: 'Formato Amazon',
          config: { mapping: 'to_amazon' },
          position: { x: 500, y: 150 },
        },
        {
          id: 'n5',
          type: 'transform',
          label: 'Formato Shopee',
          config: { mapping: 'to_shopee' },
          position: { x: 500, y: 250 },
        },
        {
          id: 'n6',
          type: 'http',
          label: 'Publicar ML',
          config: { method: 'PUT', url: '{{ML_API}}' },
          position: { x: 700, y: 50 },
        },
        {
          id: 'n7',
          type: 'http',
          label: 'Publicar Amazon',
          config: { method: 'PUT', url: '{{AMZN_API}}' },
          position: { x: 700, y: 150 },
        },
        {
          id: 'n8',
          type: 'http',
          label: 'Publicar Shopee',
          config: { method: 'PUT', url: '{{SHOPEE_API}}' },
          position: { x: 700, y: 250 },
        },
        {
          id: 'n9',
          type: 'log',
          label: 'Log Publicação',
          config: { level: 'info' },
          position: { x: 900, y: 150 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n2', target: 'n3', label: 'mercadolivre' },
        { id: 'e3', source: 'n2', target: 'n4', label: 'amazon' },
        { id: 'e4', source: 'n2', target: 'n5', label: 'shopee' },
        { id: 'e5', source: 'n3', target: 'n6' },
        { id: 'e6', source: 'n4', target: 'n7' },
        { id: 'e7', source: 'n5', target: 'n8' },
        { id: 'e8', source: 'n6', target: 'n9' },
        { id: 'e9', source: 'n7', target: 'n9' },
        { id: 'e10', source: 'n8', target: 'n9' },
      ]
    ),
  },
  {
    id: 'tpl-order-processing',
    name: 'Order Processing Pipeline',
    description: 'Processa novos pedidos: valida, reserva estoque, gera NF-e e notifica cliente.',
    category: 'Pedidos',
    tags: ['pedidos', 'nfe', 'estoque', 'cliente'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'webhook',
          label: 'Novo Pedido',
          config: { path: '/order' },
          position: { x: 100, y: 100 },
        },
        {
          id: 'n2',
          type: 'validate',
          label: 'Validar Pedido',
          config: { schema: 'order_schema' },
          position: { x: 300, y: 100 },
        },
        {
          id: 'n3',
          type: 'http',
          label: 'Reservar Estoque',
          config: { method: 'POST', url: '{{WMS}}/reserve' },
          position: { x: 500, y: 100 },
        },
        {
          id: 'n4',
          type: 'condition',
          label: 'Estoque Disponível?',
          config: { expression: 'reserved === true' },
          position: { x: 700, y: 100 },
        },
        {
          id: 'n5',
          type: 'http',
          label: 'Gerar NF-e',
          config: { method: 'POST', url: '{{FISCAL}}/nfe' },
          position: { x: 900, y: 50 },
        },
        {
          id: 'n6',
          type: 'notification',
          label: 'Pedido Confirmado',
          config: { channel: 'email', template: 'order_confirmed' },
          position: { x: 1100, y: 50 },
        },
        {
          id: 'n7',
          type: 'notification',
          label: 'Sem Estoque',
          config: { channel: 'email', template: 'out_of_stock' },
          position: { x: 900, y: 200 },
        },
        {
          id: 'n8',
          type: 'log',
          label: 'Log Pedido',
          config: { level: 'info' },
          position: { x: 1300, y: 50 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n2', target: 'n3' },
        { id: 'e3', source: 'n3', target: 'n4' },
        { id: 'e4', source: 'n4', target: 'n5', label: 'true' },
        { id: 'e5', source: 'n4', target: 'n7', label: 'false' },
        { id: 'e6', source: 'n5', target: 'n6' },
        { id: 'e7', source: 'n6', target: 'n8' },
      ]
    ),
  },
  {
    id: 'tpl-inventory-sync',
    name: 'Inventory Multi-Source Sync',
    description:
      'Consolida estoque de múltiplos depósitos e atualiza todos os canais de venda simultaneamente.',
    category: 'Estoque',
    tags: ['estoque', 'multicanal', 'deposito', 'sync'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'schedule',
          label: 'Sync A cada hora',
          config: { cron: '0 * * * *' },
          position: { x: 100, y: 150 },
        },
        {
          id: 'n2',
          type: 'http',
          label: 'Depósito Central',
          config: { method: 'GET', url: '{{WMS}}/dep/1' },
          position: { x: 300, y: 50 },
        },
        {
          id: 'n3',
          type: 'http',
          label: 'Depósito Norte',
          config: { method: 'GET', url: '{{WMS}}/dep/2' },
          position: { x: 300, y: 150 },
        },
        {
          id: 'n4',
          type: 'http',
          label: 'Depósito Sul',
          config: { method: 'GET', url: '{{WMS}}/dep/3' },
          position: { x: 300, y: 250 },
        },
        {
          id: 'n5',
          type: 'aggregate',
          label: 'Consolidar Estoque',
          config: { operation: 'sum', field: 'quantity' },
          position: { x: 550, y: 150 },
        },
        {
          id: 'n6',
          type: 'split',
          label: 'Por Canal de Venda',
          config: { channels: ['ecommerce', 'marketplace', 'loja'] },
          position: { x: 750, y: 150 },
        },
        {
          id: 'n7',
          type: 'http',
          label: 'Atualizar Ecommerce',
          config: { method: 'PUT', url: '{{ECOM}}/stock' },
          position: { x: 950, y: 50 },
        },
        {
          id: 'n8',
          type: 'http',
          label: 'Atualizar Marketplace',
          config: { method: 'PUT', url: '{{ML}}/stock' },
          position: { x: 950, y: 150 },
        },
        {
          id: 'n9',
          type: 'http',
          label: 'Atualizar Loja',
          config: { method: 'PUT', url: '{{POS}}/stock' },
          position: { x: 950, y: 250 },
        },
        {
          id: 'n10',
          type: 'log',
          label: 'Log Sync',
          config: { level: 'info' },
          position: { x: 1150, y: 150 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n1', target: 'n3' },
        { id: 'e3', source: 'n1', target: 'n4' },
        { id: 'e4', source: 'n2', target: 'n5' },
        { id: 'e5', source: 'n3', target: 'n5' },
        { id: 'e6', source: 'n4', target: 'n5' },
        { id: 'e7', source: 'n5', target: 'n6' },
        { id: 'e8', source: 'n6', target: 'n7', label: 'ecommerce' },
        { id: 'e9', source: 'n6', target: 'n8', label: 'marketplace' },
        { id: 'e10', source: 'n6', target: 'n9', label: 'loja' },
        { id: 'e11', source: 'n7', target: 'n10' },
        { id: 'e12', source: 'n8', target: 'n10' },
        { id: 'e13', source: 'n9', target: 'n10' },
      ]
    ),
  },
  {
    id: 'tpl-customer-onboarding',
    name: 'Customer Onboarding AI',
    description:
      'Onboarding inteligente: classifica cliente com IA, cria contas, envia boas-vindas personalizadas.',
    category: 'CRM',
    tags: ['cliente', 'onboarding', 'ia', 'email', 'crm'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'webhook',
          label: 'Cadastro Recebido',
          config: { path: '/signup' },
          position: { x: 100, y: 100 },
        },
        {
          id: 'n2',
          type: 'ai-classify',
          label: 'Segmentar Cliente',
          config: { model: 'claude-opus-4-8', task: 'customer_segment' },
          position: { x: 300, y: 100 },
        },
        {
          id: 'n3',
          type: 'ai-extract',
          label: 'Extrair Perfil',
          config: { model: 'claude-opus-4-8', fields: ['industry', 'size', 'needs'] },
          position: { x: 500, y: 100 },
        },
        {
          id: 'n4',
          type: 'http',
          label: 'Criar no CRM',
          config: { method: 'POST', url: '{{CRM}}/contacts' },
          position: { x: 700, y: 100 },
        },
        {
          id: 'n5',
          type: 'ai-generate',
          label: 'Gerar E-mail Personalizado',
          config: { model: 'claude-opus-4-8', template: 'welcome' },
          position: { x: 900, y: 100 },
        },
        {
          id: 'n6',
          type: 'notification',
          label: 'Enviar Boas-Vindas',
          config: { channel: 'email' },
          position: { x: 1100, y: 100 },
        },
        {
          id: 'n7',
          type: 'log',
          label: 'Log Onboarding',
          config: { level: 'info' },
          position: { x: 1300, y: 100 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n2', target: 'n3' },
        { id: 'e3', source: 'n3', target: 'n4' },
        { id: 'e4', source: 'n4', target: 'n5' },
        { id: 'e5', source: 'n5', target: 'n6' },
        { id: 'e6', source: 'n6', target: 'n7' },
      ]
    ),
  },
  {
    id: 'tpl-price-update',
    name: 'Dynamic Price Update',
    description:
      'Atualiza preços dinamicamente com base em regras de negócio e análise de concorrência via IA.',
    category: 'Precificação',
    tags: ['preco', 'dinamico', 'ia', 'concorrencia', 'ecommerce'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'schedule',
          label: 'Análise Diária',
          config: { cron: '0 8 * * *' },
          position: { x: 100, y: 100 },
        },
        {
          id: 'n2',
          type: 'http',
          label: 'Buscar Preços Concorrentes',
          config: { method: 'GET', url: '{{SCRAPER}}/prices' },
          position: { x: 300, y: 100 },
        },
        {
          id: 'n3',
          type: 'http',
          label: 'Buscar Custos ERP',
          config: { method: 'GET', url: '{{ERP}}/costs' },
          position: { x: 300, y: 250 },
        },
        {
          id: 'n4',
          type: 'ai-classify',
          label: 'Analisar Posicionamento',
          config: { model: 'claude-opus-4-8', task: 'price_positioning' },
          position: { x: 550, y: 175 },
        },
        {
          id: 'n5',
          type: 'transform',
          label: 'Calcular Novo Preço',
          config: { strategy: 'margin_based' },
          position: { x: 750, y: 175 },
        },
        {
          id: 'n6',
          type: 'condition',
          label: 'Dentro da Margem?',
          config: { expression: 'margin >= 0.15' },
          position: { x: 950, y: 175 },
        },
        {
          id: 'n7',
          type: 'http',
          label: 'Atualizar Preços',
          config: { method: 'PUT', url: '{{ECOM}}/prices' },
          position: { x: 1150, y: 100 },
        },
        {
          id: 'n8',
          type: 'notification',
          label: 'Alerta Margem Baixa',
          config: { channel: 'slack' },
          position: { x: 1150, y: 250 },
        },
        {
          id: 'n9',
          type: 'log',
          label: 'Log Preços',
          config: { level: 'info' },
          position: { x: 1350, y: 175 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n1', target: 'n3' },
        { id: 'e3', source: 'n2', target: 'n4' },
        { id: 'e4', source: 'n3', target: 'n4' },
        { id: 'e5', source: 'n4', target: 'n5' },
        { id: 'e6', source: 'n5', target: 'n6' },
        { id: 'e7', source: 'n6', target: 'n7', label: 'true' },
        { id: 'e8', source: 'n6', target: 'n8', label: 'false' },
        { id: 'e9', source: 'n7', target: 'n9' },
      ]
    ),
  },
  {
    id: 'tpl-returns-processing',
    name: 'Returns Processing',
    description:
      'Processa devoluções: analisa motivo com IA, atualiza estoque, emite crédito ao cliente.',
    category: 'Pedidos',
    tags: ['devolucao', 'retorno', 'ia', 'estoque', 'cliente'],
    createdAt: '2026-07-01T00:00:00Z',
    graph: makeGraph(
      [
        {
          id: 'n1',
          type: 'webhook',
          label: 'Solicitação Devolução',
          config: { path: '/return' },
          position: { x: 100, y: 100 },
        },
        {
          id: 'n2',
          type: 'ai-classify',
          label: 'Classificar Motivo',
          config: { model: 'claude-opus-4-8', task: 'return_reason' },
          position: { x: 300, y: 100 },
        },
        {
          id: 'n3',
          type: 'condition',
          label: 'Aprovação Automática?',
          config: { expression: 'score >= 0.8' },
          position: { x: 500, y: 100 },
        },
        {
          id: 'n4',
          type: 'http',
          label: 'Aprovar Devolução',
          config: { method: 'POST', url: '{{ERP}}/return/approve' },
          position: { x: 700, y: 50 },
        },
        {
          id: 'n5',
          type: 'http',
          label: 'Fila Revisão Manual',
          config: { method: 'POST', url: '{{ERP}}/return/review' },
          position: { x: 700, y: 200 },
        },
        {
          id: 'n6',
          type: 'http',
          label: 'Atualizar Estoque',
          config: { method: 'POST', url: '{{WMS}}/receive' },
          position: { x: 900, y: 50 },
        },
        {
          id: 'n7',
          type: 'http',
          label: 'Emitir Crédito',
          config: { method: 'POST', url: '{{ERP}}/credit' },
          position: { x: 1100, y: 50 },
        },
        {
          id: 'n8',
          type: 'notification',
          label: 'Notificar Cliente',
          config: { channel: 'email', template: 'return_approved' },
          position: { x: 1300, y: 50 },
        },
        {
          id: 'n9',
          type: 'log',
          label: 'Log Devolução',
          config: { level: 'info' },
          position: { x: 1500, y: 100 },
        },
      ],
      [
        { id: 'e1', source: 'n1', target: 'n2' },
        { id: 'e2', source: 'n2', target: 'n3' },
        { id: 'e3', source: 'n3', target: 'n4', label: 'true' },
        { id: 'e4', source: 'n3', target: 'n5', label: 'false' },
        { id: 'e5', source: 'n4', target: 'n6' },
        { id: 'e6', source: 'n6', target: 'n7' },
        { id: 'e7', source: 'n7', target: 'n8' },
        { id: 'e8', source: 'n8', target: 'n9' },
        { id: 'e9', source: 'n5', target: 'n9' },
      ]
    ),
  },
];

export function getTemplate(id: string): WorkflowTemplate | undefined {
  return WORKFLOW_TEMPLATES.find((t) => t.id === id);
}

export function listTemplates(category?: string): WorkflowTemplate[] {
  if (!category) return WORKFLOW_TEMPLATES;
  return WORKFLOW_TEMPLATES.filter((t) => t.category === category);
}
