/**
 * @seltriva/ai-core/recommendations
 * Recommendation System — the primary output surface of ATHENA
 *
 * All AI agents produce AIRecommendation objects. This module defines:
 *   - The recommendation type hierarchy
 *   - Recommendation lifecycle (proposed → reviewed → approved/rejected)
 *   - Recommendation stores and search
 *   - Batch recommendation handling
 *
 * CONSTRAINT: AI only recommends. It never executes.
 * The decision-engine/ module validates. Execution happens in application code.
 */

import type {
  AIResult, RecommendationId, AgentId, AIConfidenceValue,
  AIConfidenceTier, AITaskType, SessionId,
} from '../providers/index';
import type { Explanation } from '../explainability/index';
import type { ReasoningChain } from '../reasoning/index';

// ─── Core Recommendation ──────────────────────────────────────────────────

/**
 * The universal recommendation structure.
 * Every specialist agent produces typed recommendations via this wrapper.
 */
export interface AIRecommendation<TPayload = unknown> {
  readonly id: RecommendationId;
  readonly kind: RecommendationKind;
  readonly agentId: AgentId;
  readonly taskType: AITaskType;
  readonly sessionId?: SessionId;

  /** What ATHENA is recommending */
  readonly title: string;
  readonly description: string;

  /** The domain-specific recommendation payload */
  readonly payload: TPayload;

  /** Confidence from 0 to 1 */
  readonly confidence: AIConfidenceValue;
  readonly confidenceTier: AIConfidenceTier;

  /** Human-readable explanation — always present */
  readonly explanation: Explanation<TPayload>;

  /** Full reasoning chain that led to this recommendation */
  readonly reasoningChain?: ReasoningChain;

  /** Priority for action queue ordering */
  readonly priority: RecommendationPriority;

  /** Current lifecycle status */
  readonly status: RecommendationStatus;

  /** Estimated impact if the recommendation is acted on */
  readonly estimatedImpact?: RecommendationImpact;

  /** When this recommendation expires (re-analysis needed) */
  readonly expiresAt?: Date;

  readonly createdAt: Date;
  readonly reviewedAt?: Date;
  readonly reviewedBy?: string;
  readonly reviewNote?: string;
}

// ─── Recommendation Kinds ─────────────────────────────────────────────────

export type RecommendationKind =
  | 'schema-entity-classification'   // classify an entity as a CBL entity kind
  | 'schema-field-mapping'           // map a field to a CBL field kind
  | 'schema-anomaly-fix'             // fix detected schema anomaly
  | 'mapping-suggestion'             // suggest a mapping transformation
  | 'mapping-conflict-resolution'    // resolve a mapping conflict
  | 'erp-identification'             // identify the ERP system
  | 'erp-module-identification'      // identify the ERP module
  | 'sync-strategy'                  // recommend sync strategy
  | 'sync-conflict-resolution'       // resolve a sync conflict
  | 'performance-optimization'       // improve sync/query performance
  | 'security-classification'        // classify data sensitivity
  | 'security-risk-mitigation'       // address a security risk
  | 'validation-rule'                // recommend a validation rule
  | 'change-impact-assessment'       // assess impact of schema change
  | 'change-migration-plan';         // suggest migration plan for change

// ─── Priority ─────────────────────────────────────────────────────────────

export type RecommendationPriority = 'critical' | 'high' | 'medium' | 'low' | 'informational';

// ─── Status ───────────────────────────────────────────────────────────────

export type RecommendationStatus =
  | 'proposed'          // generated by AI, not yet reviewed
  | 'pending-review'    // queued for human review
  | 'approved'          // human approved — ready for execution
  | 'rejected'          // human rejected
  | 'implemented'       // action was taken (external signal)
  | 'superseded'        // replaced by a newer recommendation
  | 'expired';          // not acted on before expiration

// ─── Impact ───────────────────────────────────────────────────────────────

export interface RecommendationImpact {
  readonly level: 'critical' | 'high' | 'medium' | 'low';
  readonly description: string;
  readonly affectedEntities?: string[];
  readonly riskIfIgnored?: string;
  readonly benefitIfActed?: string;
  readonly estimatedEffortHours?: number;
}

// ─── Domain-Specific Payloads ─────────────────────────────────────────────

export interface EntityClassificationPayload {
  readonly entityName: string;
  readonly proposedCBLTerm: string;
  readonly proposedEntityKind: string;
  readonly domain: string;
  readonly alternatives: Array<{ cblTerm: string; confidence: number }>;
}

export interface FieldMappingPayload {
  readonly fieldName: string;
  readonly entityName: string;
  readonly proposedCBLTerm: string;
  readonly proposedFieldKind: string;
  readonly alternatives: Array<{ cblTerm: string; confidence: number }>;
  readonly requiresTransformation: boolean;
  readonly transformationHint?: string;
}

export interface ERPIdentificationPayload {
  readonly erpProfileId: string;
  readonly erpName: string;
  readonly vendor: string;
  readonly version?: string;
  readonly modules?: string[];
  readonly confidence: number;
  readonly identifyingSignals: string[];
}

export interface SyncStrategyPayload {
  readonly entityKind: string;
  readonly recommendedStrategy: string;
  readonly strategyKind: 'full-sync' | 'incremental' | 'delta' | 'event-driven' | 'scheduled';
  readonly recommendedBatchSize?: number;
  readonly recommendedIntervalMs?: number;
  readonly conflictResolutionStrategy: string;
  readonly rationale: string;
}

export interface PerformanceOptimizationPayload {
  readonly area: 'batch-size' | 'index' | 'caching' | 'parallelism' | 'query' | 'scheduling';
  readonly issue: string;
  readonly currentValue?: string | number;
  readonly recommendedValue?: string | number;
  readonly expectedImprovementPercent?: number;
}

export interface SecurityClassificationPayload {
  readonly fieldKind: string;
  readonly sensitivityLevel: 'public' | 'internal' | 'confidential' | 'restricted' | 'critical';
  readonly requiresEncryption: boolean;
  readonly requiresMasking: boolean;
  readonly requiresAuditLog: boolean;
  readonly regulatoryBasis: string[];
}

export interface ChangeImpactPayload {
  readonly changeType: 'add-field' | 'remove-field' | 'rename-field' | 'change-type' | 'add-entity' | 'remove-entity';
  readonly affectedEntities: string[];
  readonly affectedMappings: string[];
  readonly breakingChange: boolean;
  readonly migrationRequired: boolean;
  readonly migrationSteps?: string[];
  readonly rollbackPossible: boolean;
}

export interface ValidationRulePayload {
  readonly ruleId: string;
  readonly ruleName: string;
  readonly ruleDescription: string;
  readonly entityKinds: string[];
  readonly fieldKinds: string[];
  readonly severity: 'error' | 'warning' | 'info';
  readonly condition: string;
  readonly expectedBehavior: string;
}

// ─── Recommendation Engine ────────────────────────────────────────────────

export interface RecommendationEngine {
  /**
   * Generate recommendations for a given analysis context
   */
  generate<T>(input: RecommendationInput<T>): Promise<AIResult<AIRecommendation<T>[]>>;

  /**
   * Re-rank existing recommendations by priority and confidence
   */
  prioritize(recommendations: AIRecommendation[]): AIRecommendation[];

  /**
   * Merge overlapping or duplicate recommendations
   */
  deduplicate(recommendations: AIRecommendation[]): AIRecommendation[];

  /**
   * Filter recommendations to actionable ones above a threshold
   */
  filter(recommendations: AIRecommendation[], criteria: RecommendationFilter): AIRecommendation[];
}

export interface RecommendationInput<T> {
  readonly kind: RecommendationKind;
  readonly agentId: AgentId;
  readonly taskType: AITaskType;
  readonly context: string;
  readonly subject: string;
  readonly payload: T;
  readonly confidence: AIConfidenceValue;
  readonly reasoningChain?: ReasoningChain;
  readonly sessionId?: SessionId;
  readonly priority?: RecommendationPriority;
  readonly estimatedImpact?: RecommendationImpact;
  readonly ttlSeconds?: number;
}

export interface RecommendationFilter {
  readonly kinds?: RecommendationKind[];
  readonly statuses?: RecommendationStatus[];
  readonly minConfidence?: number;
  readonly priorities?: RecommendationPriority[];
  readonly agentIds?: AgentId[];
  readonly notExpired?: boolean;
}

// ─── Recommendation Store ─────────────────────────────────────────────────

export interface RecommendationStore {
  save(recommendation: AIRecommendation): Promise<void>;
  getById(id: RecommendationId): Promise<AIRecommendation | null>;
  findByKind(kind: RecommendationKind, limit?: number): Promise<AIRecommendation[]>;
  findByAgent(agentId: AgentId, limit?: number): Promise<AIRecommendation[]>;
  findByStatus(status: RecommendationStatus, limit?: number): Promise<AIRecommendation[]>;
  updateStatus(id: RecommendationId, status: RecommendationStatus, reviewedBy?: string, note?: string): Promise<void>;
  delete(id: RecommendationId): Promise<void>;
  count(filter?: RecommendationFilter): Promise<number>;
}

// ─── Recommendation Report ────────────────────────────────────────────────

export interface RecommendationReport {
  readonly sessionId?: SessionId;
  readonly generatedAt: Date;
  readonly totalRecommendations: number;
  readonly byKind: Partial<Record<RecommendationKind, number>>;
  readonly byPriority: Partial<Record<RecommendationPriority, number>>;
  readonly averageConfidence: number;
  readonly criticalCount: number;
  readonly pendingReviewCount: number;
  readonly recommendations: AIRecommendation[];
}
